"""add worker availability and earnings

Revision ID: 3bad9bde7e83
Revises: 73906abe989e
Create Date: 2026-09-29 18:21:33.052703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bad9bde7e83'
down_revision: Union[str, None] = '73906abe989e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'day', name='uq_worker_availability_day')
    )
    op.create_index(op.f('ix_worker_availability_id'), 'worker_availability', ['id'], unique=False)
    op.create_index(op.f('ix_worker_availability_worker_id'), 'worker_availability', ['worker_id'], unique=False)
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_earnings_id'), 'earnings', ['id'], unique=False)
    op.create_index(op.f('ix_earnings_payment_status'), 'earnings', ['payment_status'], unique=False)
    op.create_index(op.f('ix_earnings_worker_id'), 'earnings', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earnings_worker_id'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_payment_status'), table_name='earnings')
    op.drop_index(op.f('ix_earnings_id'), table_name='earnings')
    op.drop_table('earnings')
    op.drop_index(op.f('ix_worker_availability_worker_id'), table_name='worker_availability')
    op.drop_index(op.f('ix_worker_availability_id'), table_name='worker_availability')
    op.drop_table('worker_availability')
    # ### end Alembic commands ###
